a=5;
try{
    console.log(a);
}
catch
{
    console.log("Error");
}